In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.feature_selection import SelectFromModel
import matplotlib.pyplot as plt 

In [2]:
data = pd.read_csv('diamonds.csv', index_col=0)

In [3]:
data.head()

carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
train, test = train_test_split(data, test_size=0.15)

In [5]:
train, validation = train_test_split(train, test_size=0.15)

In [6]:
train_one_hot_cut = pd.get_dummies(train['cut'])
train_one_hot_color = pd.get_dummies(train['color'])
train_one_hot_clarity = pd.get_dummies(train['clarity'])

In [7]:
validation_one_hot_cut = pd.get_dummies(validation['cut'])
validation_one_hot_color = pd.get_dummies(validation['color'])
validation_one_hot_clarity = pd.get_dummies(validation['clarity'])

In [8]:
test_one_hot_cut = pd.get_dummies(test['cut'])
test_one_hot_color = pd.get_dummies(test['color'])
test_one_hot_clarity = pd.get_dummies(test['clarity'])

In [9]:
y_train = train.loc[:,'price']
y_validation = validation.loc[:,'price']
y_test = test.loc[:,'price']

In [10]:
x_train = train.drop('price', axis=1)
x_validation = validation.drop('price', axis=1)
x_test = test.drop('price', axis=1)

In [11]:
x_train = x_train.drop('cut', axis=1)
x_train = x_train.drop('color', axis=1)
x_train = x_train.drop('clarity', axis=1)

In [12]:
x_validation = x_validation.drop('cut', axis=1)
x_validation = x_validation.drop('color', axis=1)
x_validation = x_validation.drop('clarity', axis=1)

In [13]:
x_test = x_test.drop('cut', axis=1)
x_test = x_test.drop('color', axis=1)
x_test = x_test.drop('clarity', axis=1)

In [14]:
x_scaler = StandardScaler().fit(x_train)

In [15]:
x_train.head()

carat  depth  table     x     y     z
15225   1.04   61.9   57.0  6.51  6.54  4.04
25920   2.05   60.1   58.0  8.25  8.19  4.94
10870   1.15   62.4   56.0  6.70  6.74  4.19
33294   0.31   60.1   58.0  4.38  4.40  2.64
39353   0.52   63.3   55.0  5.13  5.10  3.24

In [16]:
x_test.head()

carat  depth  table     x     y     z
46171   0.50   61.3   58.0  5.12  5.06  3.12
9073    1.03   61.1   59.0  6.50  6.56  3.99
19600   1.57   62.4   57.0  7.51  7.40  4.65
51753   0.70   60.7   61.0  5.69  5.71  3.46
50636   0.23   61.0   59.0  3.95  3.99  2.42

In [17]:
x_train_norm = pd.DataFrame(x_scaler.transform(x_train), columns=x_train.columns, index=x_train.index)
x_validation_norm = pd.DataFrame(x_scaler.transform(x_validation), columns=x_validation.columns, index=x_validation.index)
x_test_norm = pd.DataFrame(x_scaler.transform(x_test), columns=x_test.columns, index=x_test.index)

In [18]:
x_train_norm.head()

carat     depth     table         x         y         z
15225  0.511974  0.105764 -0.202421  0.694728  0.698259  0.706089
25920  2.648343 -1.148395  0.246244  2.248009  2.131066  1.975421
10870  0.744648  0.454141 -0.651086  0.864339  0.871933  0.917644
33294 -1.032134 -1.148395  0.246244 -1.206701 -1.160047 -1.268427
39353 -0.587939  1.081220 -1.099751 -0.537184 -0.552190 -0.422206

In [19]:
x_test_norm.head()

carat     depth     table         x         y         z
46171 -0.630243 -0.312289  0.246244 -0.546111 -0.586924 -0.591450
9073   0.490822 -0.451640  0.694908  0.685801  0.715627  0.635571
19600  1.633039  0.454141 -0.202421  1.587418  1.445055  1.566414
51753 -0.207200 -0.730342  1.592238 -0.037278 -0.022486 -0.111925
50636 -1.201352 -0.521315  0.694908 -1.590558 -1.516078 -1.578708

In [20]:
x_train_norm = x_train_norm.join(train_one_hot_cut)
x_train_norm = x_train_norm.join(train_one_hot_color)
x_train_norm = x_train_norm.join(train_one_hot_clarity)

In [21]:
x_validation_norm = x_validation_norm.join(validation_one_hot_cut)
x_validation_norm = x_validation_norm.join(validation_one_hot_color)
x_validation_norm = x_validation_norm.join(validation_one_hot_clarity)

In [22]:
x_test_norm = x_test_norm.join(test_one_hot_cut)
x_test_norm = x_test_norm.join(test_one_hot_color)
x_test_norm = x_test_norm.join(test_one_hot_clarity)

In [23]:
x_train_norm.head()

carat     depth     table         x         y         z  Fair  Good  \
15225  0.511974  0.105764 -0.202421  0.694728  0.698259  0.706089     0     0   
25920  2.648343 -1.148395  0.246244  2.248009  2.131066  1.975421     0     0   
10870  0.744648  0.454141 -0.651086  0.864339  0.871933  0.917644     0     0   
33294 -1.032134 -1.148395  0.246244 -1.206701 -1.160047 -1.268427     0     0   
39353 -0.587939  1.081220 -1.099751 -0.537184 -0.552190 -0.422206     0     0   

       Ideal  Premium  ...   I  J  I1  IF  SI1  SI2  VS1  VS2  VVS1  VVS2  
15225      1        0  ...   0  0   0   0    1    0    0    0     0     0  
25920      0        1  ...   0  1   0   0    0    0    1    0     0     0  
10870      1        0  ...   0  0   0   0    0    1    0    0     0     0  
33294      0        1  ...   0  0   0   0    0    1    0    0     0     0  
39353      0        0  ...   1  0   0   0    1    0    0    0     0     0  

[5 rows x 26 columns]

In [24]:
x_test_norm.head()

carat     depth     table         x         y         z  Fair  Good  \
46171 -0.630243 -0.312289  0.246244 -0.546111 -0.586924 -0.591450     0     0   
9073   0.490822 -0.451640  0.694908  0.685801  0.715627  0.635571     0     0   
19600  1.633039  0.454141 -0.202421  1.587418  1.445055  1.566414     0     0   
51753 -0.207200 -0.730342  1.592238 -0.037278 -0.022486 -0.111925     0     1   
50636 -1.201352 -0.521315  0.694908 -1.590558 -1.516078 -1.578708     0     0   

       Ideal  Premium  ...   I  J  I1  IF  SI1  SI2  VS1  VS2  VVS1  VVS2  
46171      0        1  ...   0  0   0   0    0    0    0    1     0     0  
9073       0        0  ...   0  0   0   0    1    0    0    0     0     0  
19600      1        0  ...   0  1   0   0    1    0    0    0     0     0  
51753      0        0  ...   0  0   0   0    0    1    0    0     0     0  
50636      0        0  ...   0  0   0   0    0    0    0    1     0     0  

[5 rows x 26 columns]

# Normal Equation

In [25]:
theta_norm = np.dot(np.linalg.pinv(np.dot(np.transpose(x_train_norm),x_train_norm)),np.dot(np.transpose(x_train_norm),y_train))

In [26]:
y_validation_pred_normal = np.dot(theta_norm, np.transpose(x_validation_norm))

In [27]:
metrics.r2_score(y_validation, y_validation_pred_normal)

0.9135950936380198

In [28]:
metrics.mean_absolute_error(y_validation, y_validation_pred_normal)

752.9581500867752

# Linear Regression

In [175]:
learning_rate=0.0001
iterations=75

### Scikit-learn implementation

In [176]:
clf = SGDRegressor(eta0=learning_rate, max_iter=iterations,verbose=True, penalty="None", loss="squared_loss", learning_rate="constant", tol=None, shuffle=False, fit_intercept=False)

In [177]:
initial_theta = np.zeros_like(theta_norm)

In [178]:
clf.fit(x_train_norm, y_train, coef_init=initial_theta)

-- Epoch 1
Norm: 4970.23, NNZs: 26, Bias: 0.000000, T: 38971, Avg. loss: 3246386.645378
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 5623.19, NNZs: 26, Bias: 0.000000, T: 77942, Avg. loss: 1238798.395733
Total training time: 0.01 seconds.
-- Epoch 3
Norm: 5990.10, NNZs: 26, Bias: 0.000000, T: 116913, Avg. loss: 1030389.456806
Total training time: 0.01 seconds.
-- Epoch 4
Norm: 6305.25, NNZs: 26, Bias: 0.000000, T: 155884, Avg. loss: 911154.754506
Total training time: 0.02 seconds.
-- Epoch 5
Norm: 6580.56, NNZs: 26, Bias: 0.000000, T: 194855, Avg. loss: 835373.960025
Total training time: 0.03 seconds.
-- Epoch 6
Norm: 6818.20, NNZs: 26, Bias: 0.000000, T: 233826, Avg. loss: 785182.759905
Total training time: 0.03 seconds.
-- Epoch 7
Norm: 7022.28, NNZs: 26, Bias: 0.000000, T: 272797, Avg. loss: 750757.319156
Total training time: 0.04 seconds.
-- Epoch 8
Norm: 7197.58, NNZs: 26, Bias: 0.000000, T: 311768, Avg. loss: 726359.658933
Total training time: 0.04 seconds.
-- Epoch 9
Norm

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.0001,
       fit_intercept=False, l1_ratio=0.15, learning_rate='constant',
       loss='squared_loss', max_iter=75, n_iter=None, penalty='None',
       power_t=0.25, random_state=None, shuffle=False, tol=None,
       verbose=True, warm_start=False)

In [179]:
y_validation_pred_SKlearn = clf.predict(x_validation_norm)

In [180]:
metrics.r2_score(y_validation, y_validation_pred_SKlearn)

0.9135686685828697

In [181]:
metrics.mean_absolute_error(y_validation, y_validation_pred_SKlearn)

751.0297973510636

### Our implementation

In [182]:
%matplotlib qt
def SGD(theta, x, y, learning_rate, iterations):
    m = x.shape[0]
    iter_average_cost_list =[]
    fig = plt.figure(1)
    plt.xlabel('Iterations')
    plt.ylabel('Average Cost')
    plt.ion()
    plt.show()
    for i in range(1,iterations+1):
        iter_total_cost = 0
        for item,price in zip(x.values, y.values):
            y_pred = np.dot(item, theta)
            loss = y_pred - price
            cost = np.sum(loss ** 2)/2
            gradient = np.dot(item.transpose(), loss)
            theta = theta - learning_rate * gradient
            iter_total_cost += cost
        iter_average_cost = iter_total_cost/m
        iter_average_cost_list.append(iter_average_cost)
        print("Epoch {}".format(i))
        print("Cost {}".format(iter_average_cost))
        plt.scatter(i,iter_average_cost, c='b')
        fig.canvas.draw()
        plt.pause(0.0001)
        
    return theta

In [183]:
initial_theta = np.zeros_like(theta_norm)

In [184]:
theta_sgd = SGD(initial_theta, x_train_norm, y_train, learning_rate, iterations)

Epoch 1
Cost 3246386.645378153
Epoch 2
Cost 1238798.3957333039
Epoch 3
Cost 1030389.4568055258
Epoch 4
Cost 911154.7545059922
Epoch 5
Cost 835373.9600249743
Epoch 6
Cost 785182.7599053635
Epoch 7
Cost 750757.3191560082
Epoch 8
Cost 726359.6589327609
Epoch 9
Cost 708517.2139777249
Epoch 10
Cost 695072.6859800695
Epoch 11
Cost 684656.0823958575
Epoch 12
Cost 676379.6396642638
Epoch 13
Cost 669656.633317559
Epoch 14
Cost 664091.4611134426
Epoch 15
Cost 659411.7829576638
Epoch 16
Cost 655425.9824642227
Epoch 17
Cost 651996.1329022887
Epoch 18
Cost 649020.5954738858
Epoch 19
Cost 646422.6793539126
Epoch 20
Cost 644143.1611673773
Epoch 21
Cost 642135.2883210038
Epoch 22
Cost 640361.3972916703
Epoch 23
Cost 638790.5924197484
Epoch 24
Cost 637397.1280851429
Epoch 25
Cost 636159.262222449
Epoch 26
Cost 635058.429134287
Epoch 27
Cost 634078.6311595236
Epoch 28
Cost 633205.9822875559
Epoch 29
Cost 632428.3587651339
Epoch 30
Cost 631735.1262166755
Epoch 31
Cost 631116.9224087847
Epoch 32
Cost 6305

In [172]:
y_validation_pred_our = np.dot(theta_sgd, np.transpose(x_validation_norm))

In [173]:
metrics.r2_score(y_validation, y_validation_pred_our)

0.9126614704153672

In [174]:
metrics.mean_absolute_error(y_validation, y_validation_pred_our)

748.3330012441908

## Gridsearch

In [206]:
learning_rate_list = [10**i for i in range(-6,-1)]

In [207]:
learning_rate_list

[1e-06, 1e-05, 0.0001, 0.001, 0.01]

In [209]:
iterations_list = np.linspace(0, 200, 9)[1:]

In [210]:
iterations_list

array([ 25.,  50.,  75., 100., 125., 150., 175., 200.])

In [211]:
results_gridsearch = []
for learning_rate in learning_rate_list:
    for iteration in iterations_list:
        clf = SGDRegressor(eta0=learning_rate, max_iter=iteration,verbose=False, penalty="None", loss="squared_loss", learning_rate="constant", tol=None, shuffle=False, fit_intercept=False)
        initial_theta = np.zeros_like(theta_norm)
        clf.fit(x_train_norm, y_train, coef_init=initial_theta)
        y_validation_pred_SKlearn = clf.predict(x_validation_norm)
        r2_metric = metrics.r2_score(y_validation, y_validation_pred_SKlearn)
        mae_metric = metrics.mean_absolute_error(y_validation, y_validation_pred_SKlearn)
        results_gridsearch.append([learning_rate,iteration,r2_metric,mae_metric])

In [252]:
results = np.array(results_gridsearch)

In [253]:
result_idx = results[:,3].argsort()
results = results[result_idx]
results = results[results[..., 2] >= 0.7]

In [254]:
print(results)

[[1.00000000e-03 2.50000000e+01 9.12661470e-01 7.48333001e+02]
 [1.00000000e-03 5.00000000e+01 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 1.25000000e+02 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 1.00000000e+02 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 1.50000000e+02 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 1.75000000e+02 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 7.50000000e+01 9.12661474e-01 7.48333026e+02]
 [1.00000000e-03 2.00000000e+02 9.12661474e-01 7.48333026e+02]
 [1.00000000e-04 7.50000000e+01 9.13568669e-01 7.51029797e+02]
 [1.00000000e-04 1.00000000e+02 9.13586927e-01 7.51032898e+02]
 [1.00000000e-04 1.25000000e+02 9.13591395e-01 7.51045008e+02]
 [1.00000000e-04 1.50000000e+02 9.13592604e-01 7.51050502e+02]
 [1.00000000e-04 1.75000000e+02 9.13592935e-01 7.51052442e+02]
 [1.00000000e-04 2.00000000e+02 9.13593026e-01 7.51053060e+02]
 [1.00000000e-04 5.00000000e+01 9.13462458e-01 7.51368167e+02]
 [1.00000000e-04 2.50000000e+01 9.12348796e-01 7.568449

In [257]:
plt.semilogx(results[:,0],results[:,3],'.')
plt.grid()
plt.show()

## Feature Selection

In [185]:
model_sfm = SelectFromModel(clf, prefit=True)
feature_mask = model_sfm.get_support()
feature_name = np.array(x_train_norm.columns)
print(np.array(feature_name)[feature_mask==True])

['carat' 'Good' 'Ideal' 'Premium' 'Very Good' 'D' 'E' 'F' 'G' 'I1' 'IF'
 'VS1' 'VVS1' 'VVS2']


In [186]:
x_train_selected = model_sfm.transform(x_train_norm)
x_test_selected = model_sfm.transform(x_test_norm)

In [187]:
clf.fit(x_train_selected, y_train)

-- Epoch 1
Norm: 6112.56, NNZs: 14, Bias: 0.000000, T: 38971, Avg. loss: 4203252.211560
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 6927.98, NNZs: 14, Bias: 0.000000, T: 77942, Avg. loss: 1117473.269640
Total training time: 0.01 seconds.
-- Epoch 3
Norm: 7147.16, NNZs: 14, Bias: 0.000000, T: 116913, Avg. loss: 986297.078003
Total training time: 0.01 seconds.
-- Epoch 4
Norm: 7257.19, NNZs: 14, Bias: 0.000000, T: 155884, Avg. loss: 947529.769231
Total training time: 0.01 seconds.
-- Epoch 5
Norm: 7335.66, NNZs: 14, Bias: 0.000000, T: 194855, Avg. loss: 926049.468025
Total training time: 0.02 seconds.
-- Epoch 6
Norm: 7399.49, NNZs: 14, Bias: 0.000000, T: 233826, Avg. loss: 911909.152757
Total training time: 0.02 seconds.
-- Epoch 7
Norm: 7454.28, NNZs: 14, Bias: 0.000000, T: 272797, Avg. loss: 901753.586048
Total training time: 0.02 seconds.
-- Epoch 8
Norm: 7502.66, NNZs: 14, Bias: 0.000000, T: 311768, Avg. loss: 894051.089843
Total training time: 0.03 seconds.
-- Epoch 9
Norm:

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.0001,
       fit_intercept=False, l1_ratio=0.15, learning_rate='constant',
       loss='squared_loss', max_iter=75, n_iter=None, penalty='None',
       power_t=0.25, random_state=None, shuffle=False, tol=None,
       verbose=True, warm_start=False)

In [188]:
clf.score(x_test_selected, y_test)

0.89370375135579